
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvaatlzuyuegugjnjbyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2YWF0bHp1eXVlZ3Vnam5qYnljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTE3NzgsImV4cCI6MjA2MTg2Nzc3OH0.Mqk_-HtekDB2GtpgqGaQuKJf_UC4a4s99FBNXqnHoFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
